version: '3.8'

services:
  krishi-ml-server:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./model:/app/model
      - ./saved_models:/app/saved_models
      - ./labels.txt:/app/labels.txt
    environment:
      - PORT=5001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
