version: "3.8"

services:
  web:
    build:
      context: ./krishi_web
    ports:
      - "3000:3000"
    depends_on:
      - model
    env_file:
      - ./krishi_web/.env.local
    environment:
      NODE_ENV: production # Changed to production for containerization

  model:
    build:
      context: ./krishi-model
    env_file:
      - ./krishi-model/.env
    ports:
      - "8000:8000"