version: "3.8"

services:
  web:
    build:
      context: ./krishi_web
    ports:
      - "3000:3000"
    depends_on:
      - model
    environment:
      NODE_ENV: development

  model:
    build:
      context: ./krishi-model
    ports:
      - "8000:8000"