apiVersion: apps/v1
kind: Deployment
metadata:
  name: krishi-model-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: krishi-model
  template:
    metadata:
      labels:
        app: krishi-model
    spec:
      containers:
        - name: krishi-model
          image: ayush183739/krishi-model:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"