apiVersion: apps/v1
kind: Deployment
metadata:
  name: krishi-model-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: krishi-model
  template:
    metadata:
      labels:
        app: krishi-model
    spec:
      containers:
        - name: krishi-model
          image: <your-docker-registry>/krishi_model  # Replace with your actual Docker image
          ports:
<<<<<<< HEAD
            - containerPort: 8000
          resources:
            requests:
              memory: "8Gi"
              cpu: "2"
            limits:
              memory: "10Gi"
              cpu: "4"
=======
            - containerPort: 8000
>>>>>>> parent of 0b1df680 (contanerization completed)
