graph TD
    subgraph User Interfaces
        subgraph Web UI
            WebApp[Web App]
            WebLocalStorage[Browser Cache]
        end

        subgraph Phone App
            MobileApp[Mobile App]
            MobileLocalStorage[Local Storage]
        end
    end

    subgraph Backend Services
        MLServer[ML Inference Server]
        Firebase[Firebase Backend]
        Supabase[Supabase Database]
        WeatherAPI[External Weather API]
    end

    MobileApp -- Image Upload, Status Request --> MLServer
    MLServer -- Prediction Results --> MobileApp
    MobileApp -- Analytics Events --> Firebase
    MobileApp -- Location Data --> WeatherAPI
    MobileApp -- Caching --> MobileLocalStorage

    WebApp -- Image Upload, Status Request --> MLServer
    MLServer -- Prediction Results --> WebApp
    WebApp -- Data Operations --> Supabase
    WebApp -- Location Data --> WeatherAPI
    WebApp -- Caching --> WebLocalStorage

    Firebase -- User Data, Analytics --> MobileApp
    Supabase -- Data --> WebApp
    WeatherAPI -- Weather Data --> MobileApp
    WeatherAPI -- Weather Data --> WebApp

    MLServer -- Training Data --> MLServer